<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RALNLQ2A" failures="1" tests="1" name="Default test(failed)" time="9.936" errors="0" timestamp="2025-05-22T15:05:01 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.717">
    <failure type="java.lang.AssertionError" message="expected [https://devapp.valianttinfo.com/company/dashboard] but found [https://devapp.valianttinfo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://devapp.valianttinfo.com/company/dashboard] but found [https://devapp.valianttinfo.com/]
at stepDefinitions.LoginTests.user_can_able_to_see_the_dashboard_page(LoginTests.java:61)
at âœ½.user can able to see the dashboard page(file:///C:/Users/V%20R%20Della/Desktop/Automation/Selenium/Practice-Cucumber/src/test/resources/features/LoginFeatures.feature:13)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test(failed) -->
